name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    env:
      YOSYS: yowasp-yosys
      NEXTPNR_ICE40: yowasp-nextpnr-ice40
      ICEPACK: yowasp-icepack
      NEXTPNR_ECP5: yowasp-nextpnr-ecp5
      ECPPACK: yowasp-ecppack
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Poetry
        run:
          pip install --upgrade pip
          pip install poetry poethepoet
      - name: Create Poetry environment
        run: |
          python -V
          poetry --version
          poetry install
      - name: Install YoWASP
        run: |
          poetry run pip install yowasp-yosys yowasp-nextpnr-ice40 yowasp-nextpnr-ecp5
      - name: Run tests
        run: poe test
